name: 6.824 mapreduce

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - name: Build and Test mapreduce
        working-directory: ./src/main
        run: |
          sh ./test-mr.sh
