name: 6.824 raft

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  GOPROXY: "https://goproxy.cn"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - name: Build and Test 2A
        working-directory: ./src/raft
        run: |
          go test -run 2A
      - name: Build and Test 2B
        working-directory: ./src/raft
        run: |
          go test -run 2B
      - name: Build and Test 2C
        working-directory: ./src/raft
        run: |
          go test -run 2C