name: 6.824

on:
  push:
    branches:
      - main
    paths:
      - '6.824/**'
  pull_request:
    branches:
      - main
    paths:
      - '6.824/**'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - name: Build and Test mapreduce
        working-directory: ./6.824/src/main
        run: |
          sh ./test-mr.sh
      - name: Build and Test 2A
        working-directory: ./6.824/src/raft
        run: |
          go test -run 2A
      - name: Build and Test 2B
        working-directory: ./6.824/src/raft
        run: |
          go test -run 2B
      - name: Build and Test 2C
        working-directory: ./6.824/src/raft
        run: |
          go test -run 2C
      - name: Build and Test 3A
        working-directory: ./6.824/src/kvraft
        run: |
          go test -run 3A -timeout 30m -short
      - name: Build and Test 3B
        working-directory: ./6.824/src/kvraft
        run: |
          go test -run 3B -timeout 30m -short
      - name: Build and Test 4A
        working-directory: ./6.824/src/shardmaster
        run: |
          go test -short
