on:
  push:
    branches:
      - main
    paths:
      - "lg/**"
  pull_request:
    paths:
      - "lg/**"

name: Continuous integration

# Golang
jobs:
  check:
    name: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lg
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lg
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Test
        run: go test -v ./...
