on:
  push:
    branches:
      - main
    paths:
      - "lt/**"
  pull_request:
    paths:
      - "lt/**"

name: Continuous integration

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lt
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "pnpm"
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm run lint
      - name: Format
        run: pnpm run fmt
      - name: Run tests
        run: pnpm run test
